### PR TITLE
Added several optimisations and changes

### PR DESCRIPTION
**Pull request by Beraliv**

### CODE REVIEW

**Comment by Kelin2025** [comment]
Thank you!
Are you planning to continue or was it a _one-time promotion_? :speak_no_evil:

**Comment by Beraliv** [comment]
@Kelin2025 I plan to go on!

**Comment by Kelin2025** [comment]
@Beraliv nice to hear it!
I sent you invite :)

**Comment by Beraliv** [comment]
@Kelin2025 Thank you!

**Pull request merged**
