### PR TITLE
New method: map. Size: 262B.

### PR DESCRIPTION
**Pull request by Beraliv**
review cc/@Kelin2025 @BabkinAleksandr

### CODE REVIEW

**Comment by Beraliv** [comment]
I suppose it should be curried

**Comment by Kelin2025** [comment]
1. Doesn't R.map work with objects too?
2. Ofc it should be curried
3. Callback should be unary (now it takes all ages from .map)
4. Due to filter/reject/map similar mechanics, it's reasonable to do some common logic

**Comment by Beraliv** [comment]
1. No, mapObj for that
2. Yeah, added
3. OK, changed type for that
4. Yeah, reasonable. It concerns our discussion about helper functions.

**Comment by Beraliv** [comment]
review again cc/@Kelin2025 @BabkinAleksandr

**Pull request merged**
